-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\HBF_64_test_simulink\castSection.vhd
-- Created: 2021-12-08 13:38:15
-- 
-- Generated by MATLAB 9.10 and HDL Coder 3.18
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: castSection
-- Source Path: HBF_64_test_simulink/HBF_x8/hb0a/CICDecimation/castSection
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY castSection IS
  PORT( gcOut_re                          :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        gcOut_im                          :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        dataOut_re                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En13
        dataOut_im                        :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En13
        );
END castSection;


ARCHITECTURE rtl OF castSection IS

  -- Signals
  SIGNAL gcOut_re_signed                  : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL dataOut_re_tmp                   : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL gcOut_im_signed                  : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL dataOut_im_tmp                   : signed(15 DOWNTO 0);  -- sfix16_En13

BEGIN
  gcOut_re_signed <= signed(gcOut_re);

  
  dataOut_re_tmp <= X"7FFF" WHEN (gcOut_re_signed(17) = '0') AND (gcOut_re_signed(16 DOWNTO 2) = "111111111111111") ELSE
      gcOut_re_signed(17 DOWNTO 2) + ('0' & gcOut_re_signed(1));

  dataOut_re <= std_logic_vector(dataOut_re_tmp);

  gcOut_im_signed <= signed(gcOut_im);

  
  dataOut_im_tmp <= X"7FFF" WHEN (gcOut_im_signed(17) = '0') AND (gcOut_im_signed(16 DOWNTO 2) = "111111111111111") ELSE
      gcOut_im_signed(17 DOWNTO 2) + ('0' & gcOut_im_signed(1));

  dataOut_im <= std_logic_vector(dataOut_im_tmp);

END rtl;

