-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\HBF_64_test_simulink\dsSection.vhd
-- Created: 2021-12-08 13:38:15
-- 
-- Generated by MATLAB 9.10 and HDL Coder 3.18
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dsSection
-- Source Path: HBF_64_test_simulink/HBF_x8/hb0a/CICDecimation/dsSection
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.HBF_x8_pkg.ALL;

ENTITY dsSection IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        integOut_re                       :   IN    vector_of_std_logic_vector18(0 TO 1);  -- sfix18_En15 [2]
        integOut_im                       :   IN    vector_of_std_logic_vector18(0 TO 1);  -- sfix18_En15 [2]
        i_vout                            :   IN    std_logic;
        i_rstout                          :   IN    std_logic;
        dsOut_re                          :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        dsOut_im                          :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        ds_vout                           :   OUT   std_logic
        );
END dsSection;


ARCHITECTURE rtl OF dsSection IS

  -- Functions
  -- HDLCODER_TO_STDLOGIC 
  FUNCTION hdlcoder_to_stdlogic(arg: boolean) RETURN std_logic IS
  BEGIN
    IF arg THEN
      RETURN '1';
    ELSE
      RETURN '0';
    END IF;
  END FUNCTION;


  -- Signals
  SIGNAL integOut_re_signed               : vector_of_signed18(0 TO 1);  -- sfix18_En15 [2]
  SIGNAL integOut_im_signed               : vector_of_signed18(0 TO 1);  -- sfix18_En15 [2]
  SIGNAL decimate_countds                 : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL dsOut_re_tmp                     : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL dsOut_im_tmp                     : signed(17 DOWNTO 0);  -- sfix18_En15

BEGIN
  outputgen1: FOR k IN 0 TO 1 GENERATE
    integOut_re_signed(k) <= signed(integOut_re(k));
  END GENERATE;

  outputgen: FOR k IN 0 TO 1 GENERATE
    integOut_im_signed(k) <= signed(integOut_im(k));
  END GENERATE;

  decimate_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      decimate_countds <= to_unsigned(16#000#, 11);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF ((decimate_countds = to_unsigned(16#000#, 11)) AND (i_vout /= '0')) OR (i_rstout /= '0') THEN 
          decimate_countds <= to_unsigned(16#000#, 11);
        ELSIF i_vout /= '0' THEN 
          decimate_countds <= decimate_countds + to_unsigned(16#001#, 11);
        END IF;
      END IF;
    END IF;
  END PROCESS decimate_process;

  ds_vout <= hdlcoder_to_stdlogic(((decimate_countds = to_unsigned(16#000#, 11)) AND (i_vout /= '0')) AND ( NOT (i_rstout /= '0')));
  dsOut_re_tmp <= integOut_re_signed(0);
  dsOut_im_tmp <= integOut_im_signed(0);

  dsOut_re <= std_logic_vector(dsOut_re_tmp);

  dsOut_im <= std_logic_vector(dsOut_im_tmp);

END rtl;

