-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\HBF_64_test_simulink\FilterCoef.vhd
-- Created: 2021-12-08 13:38:15
-- 
-- Generated by MATLAB 9.10 and HDL Coder 3.18
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FilterCoef
-- Source Path: HBF_64_test_simulink/HBF_x8/hb0b/FIR Decimation HDL Optimized/FilterBank/FilterCoef
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.HBF_x8_pkg.ALL;

ENTITY FilterCoef IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        validIn                           :   IN    std_logic;
        syncReset                         :   IN    std_logic;
        CoefOut                           :   OUT   vector_of_std_logic_vector8(0 TO 17)  -- sfix8_En8 [18]
        );
END FilterCoef;


ARCHITECTURE rtl OF FilterCoef IS

  -- Constants
  CONSTANT Coef_table_table_data          : vector_of_signed8(0 TO 1) := 
    (to_signed(16#00#, 8), to_signed(-16#02#, 8));  -- sfix8 [2]
  CONSTANT Coef_table_table_data_2        : vector_of_signed8(0 TO 1) := 
    (to_signed(-16#06#, 8), to_signed(-16#02#, 8));  -- sfix8 [2]
  CONSTANT Coef_table_table_data_4        : vector_of_signed8(0 TO 1) := 
    (to_signed(16#08#, 8), to_signed(16#00#, 8));  -- sfix8 [2]
  CONSTANT Coef_table_table_data_6        : vector_of_signed8(0 TO 1) := 
    (to_signed(-16#0A#, 8), to_signed(16#06#, 8));  -- sfix8 [2]
  CONSTANT Coef_table_table_data_8        : vector_of_signed8(0 TO 1) := 
    (to_signed(16#00#, 8), to_signed(-16#14#, 8));  -- sfix8 [2]
  CONSTANT Coef_table_table_data_10       : vector_of_signed8(0 TO 1) := 
    (to_signed(16#60#, 8), to_signed(16#32#, 8));  -- sfix8 [2]
  CONSTANT Coef_table_table_data_12       : vector_of_signed8(0 TO 1) := 
    (to_signed(16#32#, 8), to_signed(16#60#, 8));  -- sfix8 [2]
  CONSTANT Coef_table_table_data_14       : vector_of_signed8(0 TO 1) := 
    (to_signed(-16#14#, 8), to_signed(16#00#, 8));  -- sfix8 [2]
  CONSTANT Coef_table_table_data_16       : vector_of_signed8(0 TO 1) := 
    (to_signed(16#06#, 8), to_signed(-16#0A#, 8));  -- sfix8 [2]
  CONSTANT Coef_table_table_data_18       : vector_of_signed8(0 TO 1) := 
    (to_signed(16#00#, 8), to_signed(16#08#, 8));  -- sfix8 [2]
  CONSTANT Coef_table_table_data_20       : vector_of_signed8(0 TO 1) := 
    (to_signed(-16#02#, 8), to_signed(-16#06#, 8));  -- sfix8 [2]
  CONSTANT Coef_table_table_data_22       : vector_of_signed8(0 TO 1) := 
    (to_signed(-16#02#, 8), to_signed(16#00#, 8));  -- sfix8 [2]

  -- Signals
  SIGNAL CoefAddr_cnt                     : std_logic;  -- ufix1
  SIGNAL CoefAddr_state                   : std_logic;  -- ufix1
  SIGNAL CoefAddr_cnt_next                : std_logic;  -- ufix1
  SIGNAL CoefAddr_state_next              : std_logic;  -- ufix1
  SIGNAL CoefAddr_1                       : std_logic;  -- ufix1
  SIGNAL CoefData                         : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL CoefReg                          : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL CoefData_1                       : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL CoefReg_1                        : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL Coef_table_cast                  : signed(31 DOWNTO 0);  -- int32
  SIGNAL CoefData_2                       : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL CoefReg_2                        : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL CoefData_3                       : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL CoefReg_3                        : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL Coef_table_cast_1                : signed(31 DOWNTO 0);  -- int32
  SIGNAL CoefData_4                       : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL CoefReg_4                        : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL Coef_table_cast_2                : signed(31 DOWNTO 0);  -- int32
  SIGNAL CoefData_5                       : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL CoefReg_5                        : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL Coef_table_cast_3                : signed(31 DOWNTO 0);  -- int32
  SIGNAL CoefData_6                       : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL CoefReg_6                        : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL Coef_table_cast_4                : signed(31 DOWNTO 0);  -- int32
  SIGNAL CoefData_7                       : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL CoefReg_7                        : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL Coef_table_cast_5                : signed(31 DOWNTO 0);  -- int32
  SIGNAL CoefData_8                       : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL CoefReg_8                        : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL Coef_table_cast_6                : signed(31 DOWNTO 0);  -- int32
  SIGNAL CoefData_9                       : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL CoefReg_9                        : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL Coef_table_cast_7                : signed(31 DOWNTO 0);  -- int32
  SIGNAL CoefData_10                      : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL CoefReg_10                       : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL Coef_table_cast_8                : signed(31 DOWNTO 0);  -- int32
  SIGNAL CoefData_11                      : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL CoefReg_11                       : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL Coef_table_cast_9                : signed(31 DOWNTO 0);  -- int32
  SIGNAL CoefData_12                      : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL CoefReg_12                       : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL Coef_table_cast_10               : signed(31 DOWNTO 0);  -- int32
  SIGNAL CoefData_13                      : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL CoefReg_13                       : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL CoefData_14                      : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL CoefReg_14                       : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL Coef_table_cast_11               : signed(31 DOWNTO 0);  -- int32
  SIGNAL CoefData_15                      : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL CoefReg_15                       : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL CoefData_16                      : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL CoefReg_16                       : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL CoefData_17                      : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL CoefReg_17                       : signed(7 DOWNTO 0);  -- sfix8_En8
  SIGNAL CoefOut_tmp                      : vector_of_signed8(0 TO 17);  -- sfix8_En8 [18]

BEGIN
  -- CoefAddr
  CoefAddr_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      CoefAddr_cnt <= '0';
      CoefAddr_state <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF syncReset = '1' THEN
          CoefAddr_cnt <= '0';
          CoefAddr_state <= '0';
        ELSE 
          CoefAddr_cnt <= CoefAddr_cnt_next;
          CoefAddr_state <= CoefAddr_state_next;
        END IF;
      END IF;
    END IF;
  END PROCESS CoefAddr_process;

  CoefAddr_output : PROCESS (CoefAddr_cnt, CoefAddr_state, validIn)
    VARIABLE add_cast : unsigned(1 DOWNTO 0);
    VARIABLE add_temp : unsigned(1 DOWNTO 0);
  BEGIN
    add_temp := to_unsigned(16#0#, 2);
    add_cast := to_unsigned(16#0#, 2);
    CoefAddr_cnt_next <= CoefAddr_cnt;
    CoefAddr_state_next <= CoefAddr_state;
    CoefAddr_1 <= CoefAddr_cnt;
    CASE CoefAddr_state IS
      WHEN '0' =>
        CoefAddr_state_next <= '0';
        CoefAddr_cnt_next <= '0';
        IF validIn = '1' THEN 
          CoefAddr_state_next <= '1';
        END IF;
      WHEN '1' =>
        CoefAddr_state_next <= '1';
        IF validIn = '1' THEN 
          IF CoefAddr_cnt = '1' THEN 
            CoefAddr_cnt_next <= '0';
          ELSE 
            add_cast := '0' & CoefAddr_cnt;
            add_temp := add_cast + to_unsigned(16#1#, 2);
            CoefAddr_cnt_next <= add_temp(0);
          END IF;
        END IF;
      WHEN OTHERS => 
        CoefAddr_cnt_next <= '0';
        CoefAddr_state_next <= '0';
    END CASE;
  END PROCESS CoefAddr_output;


  -- CoefTable_1
  CoefData <= to_signed(16#00#, 8);

  FilterCoef_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      CoefReg <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        CoefReg <= CoefData;
      END IF;
    END IF;
  END PROCESS FilterCoef_1_process;


  -- CoefTable_2
  CoefData_1 <= to_signed(16#00#, 8);

  FilterCoef_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      CoefReg_1 <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        CoefReg_1 <= CoefData_1;
      END IF;
    END IF;
  END PROCESS FilterCoef_2_process;


  -- CoefTable_3
  Coef_table_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & CoefAddr_1;
  CoefData_2 <= Coef_table_table_data(to_integer(Coef_table_cast));

  FilterCoef_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      CoefReg_2 <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        CoefReg_2 <= CoefData_2;
      END IF;
    END IF;
  END PROCESS FilterCoef_3_process;


  -- CoefTable_4
  CoefData_3 <= to_signed(16#02#, 8);

  FilterCoef_4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      CoefReg_3 <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        CoefReg_3 <= CoefData_3;
      END IF;
    END IF;
  END PROCESS FilterCoef_4_process;


  -- CoefTable_5
  Coef_table_cast_1 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & CoefAddr_1;
  CoefData_4 <= Coef_table_table_data_2(to_integer(Coef_table_cast_1));

  FilterCoef_5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      CoefReg_4 <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        CoefReg_4 <= CoefData_4;
      END IF;
    END IF;
  END PROCESS FilterCoef_5_process;


  -- CoefTable_6
  Coef_table_cast_2 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & CoefAddr_1;
  CoefData_5 <= Coef_table_table_data_4(to_integer(Coef_table_cast_2));

  FilterCoef_6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      CoefReg_5 <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        CoefReg_5 <= CoefData_5;
      END IF;
    END IF;
  END PROCESS FilterCoef_6_process;


  -- CoefTable_7
  Coef_table_cast_3 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & CoefAddr_1;
  CoefData_6 <= Coef_table_table_data_6(to_integer(Coef_table_cast_3));

  FilterCoef_7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      CoefReg_6 <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        CoefReg_6 <= CoefData_6;
      END IF;
    END IF;
  END PROCESS FilterCoef_7_process;


  -- CoefTable_8
  Coef_table_cast_4 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & CoefAddr_1;
  CoefData_7 <= Coef_table_table_data_8(to_integer(Coef_table_cast_4));

  FilterCoef_8_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      CoefReg_7 <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        CoefReg_7 <= CoefData_7;
      END IF;
    END IF;
  END PROCESS FilterCoef_8_process;


  -- CoefTable_9
  Coef_table_cast_5 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & CoefAddr_1;
  CoefData_8 <= Coef_table_table_data_10(to_integer(Coef_table_cast_5));

  FilterCoef_9_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      CoefReg_8 <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        CoefReg_8 <= CoefData_8;
      END IF;
    END IF;
  END PROCESS FilterCoef_9_process;


  -- CoefTable_10
  Coef_table_cast_6 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & CoefAddr_1;
  CoefData_9 <= Coef_table_table_data_12(to_integer(Coef_table_cast_6));

  FilterCoef_10_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      CoefReg_9 <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        CoefReg_9 <= CoefData_9;
      END IF;
    END IF;
  END PROCESS FilterCoef_10_process;


  -- CoefTable_11
  Coef_table_cast_7 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & CoefAddr_1;
  CoefData_10 <= Coef_table_table_data_14(to_integer(Coef_table_cast_7));

  FilterCoef_11_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      CoefReg_10 <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        CoefReg_10 <= CoefData_10;
      END IF;
    END IF;
  END PROCESS FilterCoef_11_process;


  -- CoefTable_12
  Coef_table_cast_8 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & CoefAddr_1;
  CoefData_11 <= Coef_table_table_data_16(to_integer(Coef_table_cast_8));

  FilterCoef_12_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      CoefReg_11 <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        CoefReg_11 <= CoefData_11;
      END IF;
    END IF;
  END PROCESS FilterCoef_12_process;


  -- CoefTable_13
  Coef_table_cast_9 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & CoefAddr_1;
  CoefData_12 <= Coef_table_table_data_18(to_integer(Coef_table_cast_9));

  FilterCoef_13_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      CoefReg_12 <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        CoefReg_12 <= CoefData_12;
      END IF;
    END IF;
  END PROCESS FilterCoef_13_process;


  -- CoefTable_14
  Coef_table_cast_10 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & CoefAddr_1;
  CoefData_13 <= Coef_table_table_data_20(to_integer(Coef_table_cast_10));

  FilterCoef_14_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      CoefReg_13 <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        CoefReg_13 <= CoefData_13;
      END IF;
    END IF;
  END PROCESS FilterCoef_14_process;


  -- CoefTable_15
  CoefData_14 <= to_signed(16#02#, 8);

  FilterCoef_15_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      CoefReg_14 <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        CoefReg_14 <= CoefData_14;
      END IF;
    END IF;
  END PROCESS FilterCoef_15_process;


  -- CoefTable_16
  Coef_table_cast_11 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & CoefAddr_1;
  CoefData_15 <= Coef_table_table_data_22(to_integer(Coef_table_cast_11));

  FilterCoef_16_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      CoefReg_15 <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        CoefReg_15 <= CoefData_15;
      END IF;
    END IF;
  END PROCESS FilterCoef_16_process;


  -- CoefTable_17
  CoefData_16 <= to_signed(16#00#, 8);

  FilterCoef_17_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      CoefReg_16 <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        CoefReg_16 <= CoefData_16;
      END IF;
    END IF;
  END PROCESS FilterCoef_17_process;


  -- CoefTable_18
  CoefData_17 <= to_signed(16#00#, 8);

  FilterCoef_18_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      CoefReg_17 <= to_signed(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        CoefReg_17 <= CoefData_17;
      END IF;
    END IF;
  END PROCESS FilterCoef_18_process;


  CoefOut_tmp(0) <= CoefReg;
  CoefOut_tmp(1) <= CoefReg_1;
  CoefOut_tmp(2) <= CoefReg_2;
  CoefOut_tmp(3) <= CoefReg_3;
  CoefOut_tmp(4) <= CoefReg_4;
  CoefOut_tmp(5) <= CoefReg_5;
  CoefOut_tmp(6) <= CoefReg_6;
  CoefOut_tmp(7) <= CoefReg_7;
  CoefOut_tmp(8) <= CoefReg_8;
  CoefOut_tmp(9) <= CoefReg_9;
  CoefOut_tmp(10) <= CoefReg_10;
  CoefOut_tmp(11) <= CoefReg_11;
  CoefOut_tmp(12) <= CoefReg_12;
  CoefOut_tmp(13) <= CoefReg_13;
  CoefOut_tmp(14) <= CoefReg_14;
  CoefOut_tmp(15) <= CoefReg_15;
  CoefOut_tmp(16) <= CoefReg_16;
  CoefOut_tmp(17) <= CoefReg_17;

  outputgen: FOR k IN 0 TO 17 GENERATE
    CoefOut(k) <= std_logic_vector(CoefOut_tmp(k));
  END GENERATE;

END rtl;

