-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\HBF_64_test_simulink\FilterBank.vhd
-- Created: 2021-12-08 13:38:15
-- 
-- Generated by MATLAB 9.10 and HDL Coder 3.18
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FilterBank
-- Source Path: HBF_64_test_simulink/HBF_x8/hb0b/FIR Decimation HDL Optimized/FilterBank
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.HBF_x8_pkg.ALL;

ENTITY FilterBank IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        filterIn_cmplx_re                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        filterIn_cmplx_im                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        validIn                           :   IN    std_logic;
        filterOut_cmplx_re                :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        filterOut_cmplx_im                :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        filterOut_vld                     :   OUT   std_logic
        );
END FilterBank;


ARCHITECTURE rtl OF FilterBank IS

  -- Component Declarations
  COMPONENT FilterCoef
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          validIn                         :   IN    std_logic;
          syncReset                       :   IN    std_logic;
          CoefOut                         :   OUT   vector_of_std_logic_vector8(0 TO 17)  -- sfix8_En8 [18]
          );
  END COMPONENT;

  COMPONENT subFilter
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dinReg2_0_re                    :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          coefIn                          :   IN    vector_of_std_logic_vector8(0 TO 17);  -- sfix8_En8 [18]
          dinRegVld                       :   IN    std_logic;
          syncReset                       :   IN    std_logic;
          dout_1_re                       :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          doutVld                         :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : FilterCoef
    USE ENTITY work.FilterCoef(rtl);

  FOR ALL : subFilter
    USE ENTITY work.subFilter(rtl);

  -- Signals
  SIGNAL syncReset                        : std_logic;
  SIGNAL dinRegVld                        : std_logic;
  SIGNAL filterIn_cmplx_re_signed         : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL filterIn_cmplx_im_signed         : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL dinReg_0_re                      : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL dinReg2_0_re                     : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL CoefOut                          : vector_of_std_logic_vector8(0 TO 17);  -- ufix8 [18]
  SIGNAL dinReg2Vld                       : std_logic;
  SIGNAL dout_1_re                        : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL doutVlddeadOut                   : std_logic;
  SIGNAL dinReg_0_im                      : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL dinReg2_0_im                     : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL dout_1_im                        : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL doutVld                          : std_logic;

BEGIN
  u_CoefTable_1 : FilterCoef
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              validIn => validIn,
              syncReset => syncReset,
              CoefOut => CoefOut  -- sfix8_En8 [18]
              );

  u_subFilter_1_re : subFilter
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dinReg2_0_re => std_logic_vector(dinReg2_0_re),  -- sfix16_En15
              coefIn => CoefOut,  -- sfix8_En8 [18]
              dinRegVld => dinReg2Vld,
              syncReset => syncReset,
              dout_1_re => dout_1_re,  -- sfix25_En23
              doutVld => doutVlddeadOut
              );

  u_subFilter_1_im : subFilter
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dinReg2_0_re => std_logic_vector(dinReg2_0_im),  -- sfix16_En15
              coefIn => CoefOut,  -- sfix8_En8 [18]
              dinRegVld => dinReg2Vld,
              syncReset => syncReset,
              dout_1_re => dout_1_im,  -- sfix25_En23
              doutVld => doutVld
              );

  syncReset <= '0';

  intdelay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dinRegVld <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF syncReset = '1' THEN
          dinRegVld <= '0';
        ELSE 
          dinRegVld <= validIn;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_process;


  filterIn_cmplx_re_signed <= signed(filterIn_cmplx_re);

  intdelay_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dinReg_0_re <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF syncReset = '1' THEN
          dinReg_0_re <= to_signed(16#0000#, 16);
        ELSIF validIn = '1' THEN
          dinReg_0_re <= filterIn_cmplx_re_signed;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_1_process;


  intdelay_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dinReg2_0_re <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF syncReset = '1' THEN
          dinReg2_0_re <= to_signed(16#0000#, 16);
        ELSIF dinRegVld = '1' THEN
          dinReg2_0_re <= dinReg_0_re;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_2_process;


  intdelay_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dinReg2Vld <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF syncReset = '1' THEN
          dinReg2Vld <= '0';
        ELSE 
          dinReg2Vld <= dinRegVld;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_3_process;


  filterIn_cmplx_im_signed <= signed(filterIn_cmplx_im);

  intdelay_4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dinReg_0_im <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF syncReset = '1' THEN
          dinReg_0_im <= to_signed(16#0000#, 16);
        ELSIF validIn = '1' THEN
          dinReg_0_im <= filterIn_cmplx_im_signed;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_4_process;


  intdelay_5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dinReg2_0_im <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF syncReset = '1' THEN
          dinReg2_0_im <= to_signed(16#0000#, 16);
        ELSIF dinRegVld = '1' THEN
          dinReg2_0_im <= dinReg_0_im;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_5_process;


  filterOut_cmplx_re <= dout_1_re;

  filterOut_cmplx_im <= dout_1_im;

  filterOut_vld <= doutVld;

END rtl;

