-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\HBF_64_test_simulink\FilterTapSystolicWvldin_block.vhd
-- Created: 2021-12-08 13:38:15
-- 
-- Generated by MATLAB 9.10 and HDL Coder 3.18
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FilterTapSystolicWvldin_block
-- Source Path: HBF_64_test_simulink/HBF_x8/hb0c/FIR Decimation HDL Optimized/FilterBank/subFilter/FilterTapSystolicWvldin
-- Hierarchy Level: 5
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY FilterTapSystolicWvldin_block IS
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        dinReg2_0_re                      :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        coefIn_0                          :   IN    std_logic_vector(7 DOWNTO 0);  -- sfix8_En7
        addin                             :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En22
        dinRegVld                         :   IN    std_logic;
        dinDly2                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        tapout                            :   OUT   std_logic_vector(23 DOWNTO 0)  -- sfix24_En22
        );
END FilterTapSystolicWvldin_block;


ARCHITECTURE rtl OF FilterTapSystolicWvldin_block IS

  -- Signals
  SIGNAL dinReg2_0_re_signed              : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL coefIn_0_signed                  : signed(7 DOWNTO 0);  -- sfix8_En7
  SIGNAL addin_signed                     : signed(23 DOWNTO 0);  -- sfix24_En22
  SIGNAL fTap_din_reg1                    : signed(15 DOWNTO 0) := to_signed(16#0000#, 16);  -- sfix16
  SIGNAL fTap_coef_reg1                   : signed(7 DOWNTO 0) := to_signed(16#00#, 8);  -- sfix8
  SIGNAL fTap_din_reg2                    : signed(15 DOWNTO 0) := to_signed(16#0000#, 16);  -- sfix16
  SIGNAL fTap_coef_reg2                   : signed(7 DOWNTO 0) := to_signed(16#00#, 8);  -- sfix8
  SIGNAL fTap_mult_reg                    : signed(23 DOWNTO 0) := to_signed(16#000000#, 24);  -- sfix24
  SIGNAL fTap_addout_reg                  : signed(23 DOWNTO 0) := to_signed(16#000000#, 24);  -- sfix24
  SIGNAL fTap_din_reg1_next               : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL fTap_coef_reg1_next              : signed(7 DOWNTO 0);  -- sfix8_En7
  SIGNAL fTap_din_reg2_next               : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL fTap_coef_reg2_next              : signed(7 DOWNTO 0);  -- sfix8_En7
  SIGNAL fTap_mult_reg_next               : signed(23 DOWNTO 0);  -- sfix24_En22
  SIGNAL fTap_addout_reg_next             : signed(23 DOWNTO 0);  -- sfix24_En22
  SIGNAL dinDly2_tmp                      : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL tapout_tmp                       : signed(23 DOWNTO 0);  -- sfix24_En22

BEGIN
  dinReg2_0_re_signed <= signed(dinReg2_0_re);

  coefIn_0_signed <= signed(coefIn_0);

  addin_signed <= signed(addin);

  -- FilterTapSystlicWvldIn
  fTap_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        fTap_din_reg1 <= fTap_din_reg1_next;
        fTap_coef_reg1 <= fTap_coef_reg1_next;
        fTap_din_reg2 <= fTap_din_reg2_next;
        fTap_coef_reg2 <= fTap_coef_reg2_next;
        fTap_mult_reg <= fTap_mult_reg_next;
        fTap_addout_reg <= fTap_addout_reg_next;
      END IF;
    END IF;
  END PROCESS fTap_process;

  fTap_output : PROCESS (addin_signed, coefIn_0_signed, dinReg2_0_re_signed, dinRegVld, fTap_addout_reg,
       fTap_coef_reg1, fTap_coef_reg2, fTap_din_reg1, fTap_din_reg2,
       fTap_mult_reg)
  BEGIN
    fTap_din_reg1_next <= fTap_din_reg1;
    fTap_coef_reg1_next <= fTap_coef_reg1;
    fTap_din_reg2_next <= fTap_din_reg2;
    fTap_coef_reg2_next <= fTap_coef_reg2;
    fTap_mult_reg_next <= fTap_mult_reg;
    fTap_addout_reg_next <= fTap_addout_reg;
    IF dinRegVld = '1' THEN 
      fTap_addout_reg_next <= fTap_mult_reg + addin_signed;
      fTap_mult_reg_next <= fTap_din_reg2 * fTap_coef_reg2;
      fTap_din_reg2_next <= fTap_din_reg1;
      fTap_coef_reg2_next <= fTap_coef_reg1;
      fTap_din_reg1_next <= dinReg2_0_re_signed;
      fTap_coef_reg1_next <= coefIn_0_signed;
    END IF;
    dinDly2_tmp <= fTap_din_reg2;
    tapout_tmp <= fTap_addout_reg;
  END PROCESS fTap_output;


  dinDly2 <= std_logic_vector(dinDly2_tmp);

  tapout <= std_logic_vector(tapout_tmp);

END rtl;

