-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\HBF_64_test_simulink\FIR_Decimation_HDL_Optimized_block.vhd
-- Created: 2021-12-08 13:38:15
-- 
-- Generated by MATLAB 9.10 and HDL Coder 3.18
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FIR_Decimation_HDL_Optimized_block
-- Source Path: HBF_64_test_simulink/HBF_x8/hb0c/FIR Decimation HDL Optimized
-- Hierarchy Level: 2
-- 
-- HDLFIRDeciamtion
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY FIR_Decimation_HDL_Optimized_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn_re                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        dataIn_im                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        validIn                           :   IN    std_logic;
        dataOut_re                        :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24_En22
        dataOut_im                        :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24_En22
        validOut                          :   OUT   std_logic
        );
END FIR_Decimation_HDL_Optimized_block;


ARCHITECTURE rtl OF FIR_Decimation_HDL_Optimized_block IS

  -- Component Declarations
  COMPONENT FilterBank_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          filterIn_cmplx_re               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          filterIn_cmplx_im               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          validIn                         :   IN    std_logic;
          filterOut_cmplx_re              :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24_En22
          filterOut_cmplx_im              :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24_En22
          filterOut_vld                   :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT FIRDecimInteg_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          filterOut_cmplx_re              :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En22
          filterOut_cmplx_im              :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En22
          filterOut_vld                   :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24_En22
          dataOut_im                      :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24_En22
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : FilterBank_block
    USE ENTITY work.FilterBank_block(rtl);

  FOR ALL : FIRDecimInteg_block
    USE ENTITY work.FIRDecimInteg_block(rtl);

  -- Signals
  SIGNAL filterOut_cmplx_re               : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL filterOut_cmplx_im               : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL filterOut_vld                    : std_logic;
  SIGNAL dataOut_re_tmp                   : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL dataOut_im_tmp                   : std_logic_vector(23 DOWNTO 0);  -- ufix24

BEGIN
  u_FilterBank : FilterBank_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              filterIn_cmplx_re => dataIn_re,  -- sfix16_En15
              filterIn_cmplx_im => dataIn_im,  -- sfix16_En15
              validIn => validIn,
              filterOut_cmplx_re => filterOut_cmplx_re,  -- sfix24_En22
              filterOut_cmplx_im => filterOut_cmplx_im,  -- sfix24_En22
              filterOut_vld => filterOut_vld
              );

  u_FirDecimInteg : FIRDecimInteg_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              filterOut_cmplx_re => filterOut_cmplx_re,  -- sfix24_En22
              filterOut_cmplx_im => filterOut_cmplx_im,  -- sfix24_En22
              filterOut_vld => filterOut_vld,
              dataOut_re => dataOut_re_tmp,  -- sfix24_En22
              dataOut_im => dataOut_im_tmp,  -- sfix24_En22
              validOut => validOut
              );

  dataOut_re <= dataOut_re_tmp;

  dataOut_im <= dataOut_im_tmp;

END rtl;

