-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\HBF_64_test_simulink\gcSection.vhd
-- Created: 2021-12-08 13:38:15
-- 
-- Generated by MATLAB 9.10 and HDL Coder 3.18
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: gcSection
-- Source Path: HBF_64_test_simulink/HBF_x8/hb0a/CICDecimation/gcSection
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY gcSection IS
  PORT( combOut_re                        :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        combOut_im                        :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        gcOut_re                          :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        gcOut_im                          :   OUT   std_logic_vector(17 DOWNTO 0)  -- sfix18_En15
        );
END gcSection;


ARCHITECTURE rtl OF gcSection IS

BEGIN
  gcOut_re <= combOut_re;

  gcOut_im <= combOut_im;

END rtl;

